add 4-1
Vinogradov-Mikhail/Semestr4 pull request #10
Opened 2017-03-19 20:07 UTC by Vinogradov-Mikhail

2017-03-20 10:30 UTC, yurii-litvinov requested changes
В целом всё так, но хочется, чтобы юнит-тесты были настоящими юнит-тестами (то есть их можно было запускать через Test -> Run all tests в Visual Studio)

2017-03-26 11:08 UTC, Vinogradov-Mikhail commented
а здесь тоже отдельным файлом сделать?

2017-03-26 11:30 UTC, yurii-litvinov commented
Ага

2017-04-29 17:44 UTC, yurii-litvinov approved these changes

2017-04-29 17:44 UTC, yurii-litvinov commented on 4_1/4_1/Tets.fs
> +﻿module Tets
Tets :)

2017-04-29 18:43 UTC, merged