add 6-1
Vinogradov-Mikhail/Semestr4 pull request #20
Opened 2017-05-23 21:55 UTC by Vinogradov-Mikhail

2017-05-25 20:03 UTC, yurii-litvinov requested changes
Ещё нужны юнит-тесты

2017-05-25 20:03 UTC, yurii-litvinov commented on 6-1/6-1/Program.fs
> +type LocalNetwork(newNetOfComp : List<Computer>, mat : bool[,])=
Я бы сказал, что тут не хватает комментариев

2017-05-25 20:03 UTC, yurii-litvinov commented on 6-1/6-1/Program.fs
> +                            if(rand.Next(1, 100) <= listOfAllComputersInNet.[j].operatingSystem.InfectionProbability) then
Пробела не хватает

2017-05-25 20:03 UTC, yurii-litvinov commented on 6-1/6-1/Program.fs
> +                        if (matrixOfLink.[i,j] && (listOfAllComputersInNet.[j].Infected = false) && (listOfComputersInfectedInThisStep.Contains(listOfAllComputersInNet.[j]) = false)) then
`not listOfAllComputersInNet.[j].Infected` вместо `listOfAllComputersInNet.[j].Infected = false` было бы симпатичнее

2017-05-25 20:03 UTC, yurii-litvinov commented on 6-1/6-1/Program.fs
> +           (i = 0)
Это же какая-то агрегатная операция, типа ForAll или как там оно называется. Ну в крайнем случае, fold

2017-05-25 20:03 UTC, yurii-litvinov commented on 6-1/6-1/Program.fs
> +type LocalNetwork(newNetOfComp : List<Computer>, mat : bool[,])=
И Вам чем-то больше нравится System.Collections.Generic.List вместо F#-овского списка, или это случайность?

2017-05-25 21:33 UTC, Vinogradov-Mikhail commented on 6-1/6-1/Program.fs
> +                        if (matrixOfLink.[i,j] && (listOfAllComputersInNet.[j].Infected = false) && (listOfComputersInfectedInThisStep.Contains(listOfAllComputersInNet.[j]) = false)) then
вот как оказывается

2017-05-25 21:49 UTC, yurii-litvinov requested changes
А тесты? :)

2017-05-26 05:22 UTC, yurii-litvinov requested changes

2017-05-26 05:22 UTC, yurii-litvinov commented on 6-1/6-1/Test.fs
> +    network.VirusInfection()
А что проверяется этим тестом? :) Ничего не делающий код его тоже пройдёт. Надо правильность распространения вируса по ходам проверить

2017-05-26 09:27 UTC, yurii-litvinov approved these changes
А чего оно стало 8.1? Впрочем ладно, зачтена

2017-05-26 09:33 UTC, merged