8
Vinogradov-Mikhail/Semestr4 pull request #22
Opened 2017-05-25 21:31 UTC by Vinogradov-Mikhail

2017-05-25 21:48 UTC, yurii-litvinov requested changes
Всё хорошо, но нужны юнит-тесты --- например, что действительно скачивается и находятся какие-то url-ы

2017-05-25 21:48 UTC, yurii-litvinov commented on 8-0/8-0/Program.fs
> +let paigeInfoDownloder(url : string) =
что за "paige"? :) page? И ниже так же

2017-05-25 21:58 UTC, Vinogradov-Mikhail commented on 8-0/8-0/Program.fs
> +let paigeInfoDownloder(url : string) =
это my good english

2017-05-26 05:19 UTC, yurii-litvinov approved these changes
Ожидалось что-нибудь более "архитектурное", типа разбить задачу на сбор информации и её отображение, чтобы тестировать сбор, но не буду придираться, зачтена.

2017-05-26 07:16 UTC, merged