5 4
Vinogradov-Mikhail/Semestr4 pull request #25
Opened 2017-08-25 13:49 UTC by Vinogradov-Mikhail

2017-08-26 12:28 UTC, yurii-litvinov requested changes
Надо поправить

2017-08-26 12:28 UTC, yurii-litvinov commented on 9-0/9-0/Program.fs
> -﻿module Program
Мм, если замерджить этот пуллреквест, решение задачи 9 удалится?

2017-08-26 12:28 UTC, yurii-litvinov commented on 5-4/5-4/Program.fs
> +let rec betareduction x =
мне кажется, лучше betaReduction. мелочь, но глаза режет

2017-08-26 12:28 UTC, yurii-litvinov commented on 5-4/5-4/Program.fs
> +    | Var(t) -> Var(t)
Выше нет пробелов перед "|", а тут есть, неаккуратно

2017-08-26 12:28 UTC, yurii-litvinov commented on 5-4/5-4/Program.fs
> +        |Var(s) -> App(x, y)
Можно просто Var(_), s ведь всё равно не используется

2017-08-26 12:28 UTC, yurii-litvinov commented on 5-4/5-4/5-4.fsproj
> +  <Import Project="..\..\..\..\..\..\Михаил\documents\visual studio 2015\Projects\5-4\packages\NUnit3TestAdapter.3.8.0\build\net35\NUnit3TestAdapter.props" Condition="Exists('..\..\..\..\..\..\Михаил
Так оно у меня работать не будет

2017-08-26 12:28 UTC, yurii-litvinov commented on 5-4/5-4/Program.fs
> +        |Var(s) -> App(x, y)
А в y ведь тоже могут быть редэксы. Например,
```fsharp
let ``Application``() = betareduction (App(Var "x", App(Abs("x", Var("x")), Var "x"))) |> should equal (App(Var "x", Var "x"))
```

2017-08-26 12:28 UTC, yurii-litvinov commented on 5-4/5-4/Program.fs
> +        |App(s, p) -> App(betaApp s y, p)
??

2017-08-26 12:28 UTC, yurii-litvinov commented on 5-4/5-4/Program.fs
> +                |App(q, w) -> betaApp q w
А тут мы просто забили на y? Тогда не проходит вот такое:
```fsharp
let ``application2``() = betareduction (App(Abs("s", App(Var "q", Var"s")), Var("y"))) |> should equal (App(Var "q", Var "y"))
```

2017-08-26 13:35 UTC, Vinogradov-Mikhail commented on 9-0/9-0/Program.fs
> -﻿module Program
решение для 9 я закомитил, но видимо пулл не сделал

2017-08-29 11:54 UTC, yurii-litvinov requested changes

2017-08-29 11:54 UTC, yurii-litvinov commented on 5-4V2/5-4V2/Program.fs
> +    | Abs(t, s) -> Abs(t, s)
А внутри терма в лямбда-абстракции разве не может быть редэксов? Вот Вам контрпример:
```fsharp
[<Test>]
let ``abstractionWithRedexes``() = 
    betaReduction (Abs("x", App(Abs("y", Var("y")), Var("t")))) |> should equal (Abs("x", Var "t"))
```

2017-08-29 11:54 UTC, yurii-litvinov commented on 5-4V2/5-4V2/Program.fs
> +        | App(s, p) -> App(betaApp s y, p)
А откуда это правило? :) Зачем оно меняет порядок аргументов и, например, превращает K в K*?
```fsharp
[<Test>]
let ``K a b``() = 
    betaReduction (App(App(Abs("x", Abs("y", Var "x")), Var "a"), Var "b")) |> should equal (Var "a")
```

2017-08-29 11:54 UTC, yurii-litvinov commented on 5-4V2/5-4V2/Program.fs
> +                | App(q, w) -> betaApp q y
Почему? :) Выглядит подозрительно, потому что справа нет w и нет проверки на свободные/связанные вхождения.

2017-09-05 18:16 UTC, Vinogradov-Mikhail commented
Пришлось убрать betaApp, чтобы проверка на коллизию работала корректно. Переименование переменных происходит по принципу: берется из alphabet та буква которой нет в терме.

2017-09-11 12:52 UTC, yurii-litvinov approved these changes
Достаточно похоже на правду, чтобы это можно было зачесть :) Зачтена.

2017-09-11 12:52 UTC, yurii-litvinov commented on 5-4V2/5-4V2/Program.fs
> +        | _ -> App(Var(y), s)
а внутри терма s ведь тоже могут быть редэксы? :) да и вообще, зачем отдельное правило для App(Var(y), s), мне кажется, оно покрывается последним правилом, для App(s, y)

2017-09-12 17:39 UTC, merged